name: Running Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MY_ENV_VAR: ${{ secrets.EMAIL }}
      YOUR_ENV_VAR: ${{ gihub.test_env.EMAIL }}
      
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Python 3.9.18
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.20

      - name: Install dependencies
        run: |
          pip install pytest-cov
          echo "MY_ENV_VAR: $MY_ENV_VAR"
          echo "YOUR_ENV_VAR: $YOUR_ENV_VAR"
          cd backend
          npm install
          npm run dev

      - name: Run the tests
        run: |
          cd test
          pytest
